name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest  # Use a valid runner

    strategy:
      matrix:
        node-version: [20.x, 22.x]  # Test multiple Node.js versions

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Cache dependencies

    - name: Install dependencies
      run: npm ci  # Use npm install if package-lock.json is missing

    - name: Build project
      run: npm run build --if-present  # Only runs if a build script exists

    - name: Run tests
      run: npm test
